name: Build project

on: workflow_dispatch

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android
          - AndroidAppBundle

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - if: matrix.targetPlatform == 'Android' || matrix.targetPlatform == 'AndroidAppBundle'
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload APK
        if: matrix.targetPlatform == 'Android'
        uses: actions/upload-artifact@v4
        with:
          name: Build-Android
          path: build/Android/Android

      - name: Upload AAB
        if: matrix.targetPlatform == 'AndroidAppBundle'
        uses: actions/upload-artifact@v4
        with:
          name: Build-AndroidAppBundle
          path: build/Android/AndroidAppBundle
